on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: SDKMan
        uses: sdkman/sdkman-action@v1
        id: sdkman
        with:
          candidate: java
          version: 11.0.16-zulu
      - run: java -version