on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '11.0.16'
      - name: SpotLess
        run: ./gradlew spotlessApply
      - name: grade
        uses: gradle/gradle-build-action@v2
        with:
          gradle-version: 7.4
          arguments: clean build
#      - name: build java app
#        run: 
#          ./gradlew build --scan
#          |
#          gradle init --type java-library
#          gradle clean build
      - uses: actions/upload-artifact@v3
        with:
          name: Package
          path: build/libs